# Generated by Django 4.2.5 on 2023-10-13 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_id', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField()),
                ('date_closed', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('manufacturing_ending_date', models.DateTimeField()),
                ('pack_id', models.CharField(max_length=45)),
                ('pickup_id', models.CharField(max_length=45)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateTimeField()),
                ('currency_id', models.CharField(max_length=45)),
                ('shipping_id', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('status_detail', models.TextField(blank=True, null=True)),
                ('buyer_id', models.CharField(max_length=45)),
                ('seller_id', models.CharField(max_length=45)),
                ('taxes_id', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_store', models.CharField(max_length=150)),
                ('access_token', models.CharField(max_length=254)),
                ('refresh_token', models.CharField(max_length=254)),
                ('client_id', models.CharField(max_length=150)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lojas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=30)),
                ('payer_id', models.CharField(max_length=30, null=True)),
                ('collector_id', models.CharField(max_length=30, null=True)),
                ('site_id', models.CharField(max_length=30)),
                ('card_id', models.CharField(max_length=30, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('payment_method_id', models.CharField(max_length=30)),
                ('currency_id', models.CharField(max_length=30)),
                ('installments', models.IntegerField()),
                ('coupon_id', models.CharField(max_length=30, null=True)),
                ('operation_type', models.CharField(max_length=30)),
                ('payment_type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('status_code', models.CharField(max_length=30, null=True)),
                ('status_detail', models.CharField(max_length=30)),
                ('transaction_amount', models.CharField(max_length=30)),
                ('transaction_amount_refunded', models.CharField(max_length=30, null=True)),
                ('taxes_amount', models.CharField(max_length=30, null=True)),
                ('shipping_cost', models.CharField(max_length=30, null=True)),
                ('coupon_amount', models.CharField(max_length=30, null=True)),
                ('overpaid_amount', models.CharField(max_length=30, null=True)),
                ('total_paid_amount', models.CharField(max_length=30)),
                ('installments_amount', models.CharField(max_length=30, null=True)),
                ('deferred_period', models.CharField(max_length=30, null=True)),
                ('date_approved', models.CharField(max_length=30, null=True)),
                ('authorization_code', models.CharField(max_length=30, null=True)),
                ('transaction_order_id', models.CharField(max_length=30, null=True)),
                ('date_created', models.CharField(max_length=30)),
                ('date_last_modified', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meli.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_id', models.CharField(max_length=45)),
                ('mlb_item_id', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('category_id', models.CharField(max_length=45)),
                ('variation_id', models.CharField(max_length=45)),
                ('seller_custom_field', models.CharField(max_length=45)),
                ('variation_attributes', models.TextField()),
                ('warranty', models.CharField(max_length=45)),
                ('condition', models.CharField(max_length=45)),
                ('seller_sku', models.CharField(max_length=45)),
                ('global_price', models.CharField(max_length=45)),
                ('quantity', models.CharField(max_length=45)),
                ('unit_price', models.CharField(max_length=30)),
                ('full_unit_price', models.CharField(max_length=30)),
                ('currency_id', models.CharField(max_length=45)),
                ('manufacturing_days', models.CharField(max_length=45)),
                ('sale_fee', models.CharField(max_length=45)),
                ('listing_type_id', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meli.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meli.store'),
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=254)),
                ('secret_id', models.CharField(max_length=254)),
                ('redirect_url', models.CharField(max_length=254)),
                ('location', models.CharField(choices=[('MLA', 'Argentina'), ('MLB', 'Brasil'), ('MCO', 'Colombia'), ('MCR', 'Costa Rica'), ('MEC', 'Equador'), ('MLC', 'Chile'), ('MLM', 'Mexico'), ('MLU', 'Uruguai'), ('MLV', 'Venezuela'), ('MPA', 'Panama'), ('MPE', 'Peru'), ('MPT', 'Portugal'), ('MRD', 'Republica Dominicana')], default='MLB', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
