# Generated by Django 4.2.5 on 2023-09-19 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=254)),
                ('refresh_token', models.CharField(max_length=254)),
                ('client_id', models.CharField(max_length=150)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lojas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=254)),
                ('secret_id', models.CharField(max_length=254)),
                ('redirect_url', models.CharField(max_length=254)),
                ('location', models.CharField(choices=[('MLA', 'Argentina'), ('MLB', 'Brasil'), ('MCO', 'Colombia'), ('MCR', 'Costa Rica'), ('MEC', 'Equador'), ('MLC', 'Chile'), ('MLM', 'Mexico'), ('MLU', 'Uruguai'), ('MLV', 'Venezuela'), ('MPA', 'Panama'), ('MPE', 'Peru'), ('MPT', 'Portugal'), ('MRD', 'Republica Dominicana')], default='Brasil', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
