# Generated by Django 4.2.5 on 2023-10-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='pack_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
