# Generated by Django 4.2.5 on 2023-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name_store',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='location',
            field=models.CharField(choices=[('MLA', 'Argentina'), ('MLB', 'Brasil'), ('MCO', 'Colombia'), ('MCR', 'Costa Rica'), ('MEC', 'Equador'), ('MLC', 'Chile'), ('MLM', 'Mexico'), ('MLU', 'Uruguai'), ('MLV', 'Venezuela'), ('MPA', 'Panama'), ('MPE', 'Peru'), ('MPT', 'Portugal'), ('MRD', 'Republica Dominicana')], default='MLB', max_length=3),
        ),
    ]
