# Generated by Django 4.2.5 on 2023-10-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
