# Generated by Django 4.2.5 on 2023-10-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli', '0003_payment_atm_transfer_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ml_id',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
